services:
  app-blue:
    image: andylee259/haru-app:latest
    container_name: app-blue
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=blue
      - SPRING_CONFIG_ADDITIONAL_LOCATION=file:/app/config/
    volumes:
      - /home/ubuntu/secret/temp_secret/application-secret.yml:/app/config/application-secret.yml:ro
    networks:
      - haru-network

  app-green:
    image: andylee259/haru-app:latest
    container_name: app-green
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=green
      - SPRING_CONFIG_ADDITIONAL_LOCATION=file:/app/config/
    volumes:
      - /home/ubuntu/secret/temp_secret/application-secret.yml:/app/config/application-secret.yml:ro
    networks:
      - haru-network

networks:
  haru-network:
    external: true